<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-LPT61RQN" failures="1" tests="5" name="runner.TestRunner" time="32.695" errors="0" timestamp="2021-06-08T00:40:01 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="7.638"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="18.185"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.393"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.223">
    <failure message="Test fail" type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError: Test fail
at junit.framework.Assert.fail(Assert.java:57)
at stepDef.steps.user_should_able_to_export_the_report(steps.java:77)
at âœ½.User should able to export the report(file:///C:/Users/anjan/eclipse-workspace/CucumberProject/src/test/java/features/feature2.feature:34)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.256"/>
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
